style: horizontal simple seprataor and checkbox compoenents
etalab/annuaire-entreprises-site pull request #243
Opened 2022-12-16 15:03 UTC by XavierJp

2022-12-16 16:23 UTC, XavierJp commented
Must remove ESS as it is not yet implemented on elastic

2022-12-19 14:52 UTC, yoanficadiere requested changes

2022-12-19 14:52 UTC, yoanficadiere commented on components/search-filters/index.tsx
>              { value: 'esv', label: 'Entreprise du Spectacle Vivant' },
I think **esv** is not available yet in elastic index

2022-12-19 16:40 UTC, yoanficadiere approved these changes

2022-12-19 21:58 UTC, merged