Remplace client RNA by association client
etalab/annuaire-entreprises-site pull request #333
Opened 2023-02-08 15:01 UTC by yoanficadiere

* Remplace client RNA to use api-asso 
* Display more information about association

<img width="1244" alt="Screenshot 2023-02-08 at 15 59 42" src="https://user-images.githubusercontent.com/119595487/217566785-6aec8b83-2563-458b-87f4-8bfb068b671e.png">

2023-02-08 16:17 UTC, XavierJp requested changes
I would update 

```
Pour en savoir plus...
```
with : 
```
Retrouver plus d'informations sur la fiche de cette association (lien vers la fiche) (comptes, effectifs et documents) sur data-asso.

2023-02-08 16:17 UTC, XavierJp commented on components/association-section/index.tsx
> +    ['Téléphone', telephone],
Phone, mail and siteweb should use `<a>`with mailto when relevant

2023-02-08 16:17 UTC, XavierJp commented on components/association-section/index.tsx
> +        })}
As in mockup -> would add date and and maybe agrement label

See : https://www.data-asso.fr/annuaire/association/45037469900129

2023-02-08 17:15 UTC, XavierJp commented
As soon as https://github.com/etalab/annuaire-entreprises-api-proxy/pull/9 gets deployed, we will be able to use the following route : 
`https://rncs-proxy.api.gouv.fr/association/:id_rna`

2023-02-09 08:41 UTC, XavierJp commented
NB : il va falloir également mettre a jour : 
- le changelog
- la page RNA sur le MI et expliquer d'ou vient l'API / comment la retrouver sur https://annuaire-entreprises.data.gouv.fr/sources-de-donnees/m

D'ailleurs sont-ce les données du MI ou une autre administrations ?

2023-02-09 09:32 UTC, XavierJp commented on clients/routes.ts
>    rna: {
to clean

2023-02-09 15:54 UTC, yoanficadiere commented on models/association.ts
>      );
It's look like working as expected

2023-02-09 17:00 UTC, XavierJp approved these changes
Great. Still a few fixes required but almost here

2023-02-10 10:06 UTC, yoanficadiere commented on components/header/index.tsx
> +      <div
Maybe just formatting

2023-02-10 10:10 UTC, yoanficadiere commented on components/association-section/index.tsx
> +      'Forme juridique',
i removed the line regime is undefined

2023-02-10 15:54 UTC, merged