feat: adding organisme de formation
etalab/annuaire-entreprises-site pull request #448
Opened 2023-04-16 13:19 UTC by yoanficadiere

2023-04-17 10:26 UTC, XavierJp requested changes
Il vaut mieux utiliser le client ODS existant pour tout les endpoints ODS

Quelques changements à prévoir également dans l'affichage des données

2023-04-17 10:26 UTC, XavierJp commented on clients/dgefp/index.ts
> +export const clientDGEFP = async (siren: Siren) => {
Ce serait dommage de ne pas utiliser le client open data soft qui fait notamment le travail d'aller également chercher la date de dernière mise a jour cf `odsClient`

2023-04-17 10:26 UTC, XavierJp commented on models/certifications/organismes-de-formation.ts
> +    logErrorInSentry('Error in API RGE', {
'Error in API organisme de formation'

2023-04-17 10:26 UTC, XavierJp commented on clients/dgefp/index.ts
> + */
`clientDGEFP` -> `clientOrganismeFormation`

2023-04-17 10:26 UTC, XavierJp commented on components/labels-and-certificates/qaliopi/index.tsx
> +    >
En utilisant le client ODS tu auras aussi la date de dernière mise à jour du jeu de donnée a passer en props dans la `<Section />`

2023-04-18 13:10 UTC, yoanficadiere commented on components/labels-and-certificates/qaliopi/index.tsx
> +        head={[
* J'ai utilisé la donnée `fields.denomination` comme nom de l'organisme de formation, il et parfois différent du nom de l'unité légal.
* Je ne n'est pas trouvé le nom de l'organisme certificateur dans les datas

**Pour le reste c'est ok normalement**

2023-04-18 13:14 UTC, yoanficadiere commented on components/labels-and-certificates/qaliopi/index.tsx
> +            Nous n&lsquo;avons pas trouvé les formations peuvent obtenir un
J'ai mis une string `DGEFP` pour le moment, le temps de mettre en ligne la page de DGEFP

2023-04-19 15:03 UTC, XavierJp requested changes
Quelques petits détails de sources & cie et on est bon

2023-04-19 15:03 UTC, XavierJp commented on components/labels-and-certificates/qaliopi/index.tsx
> +            DGEFP
On va plutot mettre le MTPEI plutot que la DGEFP.  Car il existe déjà

`<MTPEI />`

2023-04-19 15:03 UTC, XavierJp commented on components/labels-and-certificates/qaliopi/index.tsx
> +          sources={[EAdministration.ADEME]}
`sources={[EAdministration.MTPEI]}`

2023-04-19 15:03 UTC, XavierJp commented on components/labels-and-certificates/qaliopi/index.tsx
> +      sources={[EAdministration.MTPEI, EAdministration.DINUM]}
Mettons uniquement le MTPEI car si il y a une erreur dans les données eux seuls peuvent la modifier

2023-04-20 08:52 UTC, XavierJp approved these changes

2023-04-20 08:53 UTC, merged